#!/usr/bin/python3.9
import sys

# adding Folder_2 to the system path
sys.path.insert(0, '/usr/lib/MailLog2MySQL')
    
from ProcessLog import ProcessLog
logfile = open("/var/log/syslog","r")
# read_lines(logfile)

ProcessLog.main()
